In [4]:
import numpy as np

# Vector Operations

In [20]:
u = np.array([2,3,5,6]) # row vector

In [21]:
u

array([2, 3, 5, 6])

In [22]:
v = np.array([1,0,0,2]) # row vector

In [23]:
v

array([1, 0, 0, 2])

In [24]:
# add two vector element wise
u + v

array([3, 3, 5, 8])

In [26]:
# multiply two vector element wise
u * v

array([ 2,  0,  0, 12])

In [27]:
u.shape[0]

4

In [28]:
v.shape[0]

4

# Vector-Vector Multiplication (Dot Product)

In [34]:
# Note (Rules): (u[0]*v[0]) + (u[1]*v[1]) + .... + (u[n]*v[n]) then return a single value not vector

def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]
        
    return result

In [35]:
vector_vector_multiplication(u,v)

14.0

In [37]:
# Have a built in function like same as my custom vector_vector_multiplication() function
u.dot(v) 

14