In [4]:
import numpy as np

# Vector Operations

In [20]:
u = np.array([2,3,5,6]) # row vector

In [21]:
u

array([2, 3, 5, 6])

In [22]:
v = np.array([1,0,0,2]) # row vector

In [23]:
v

array([1, 0, 0, 2])

In [24]:
# add two vector element wise
u + v

array([3, 3, 5, 8])

In [26]:
# multiply two vector element wise
u * v

array([ 2,  0,  0, 12])

In [47]:
u.shape

(4,)

In [49]:
u.shape[0]

4

In [28]:
v.shape[0]

4

# Vector-Vector Multiplication (Dot Product)

In [40]:
# Note (Rules): (u[0]*v[0]) + (u[1]*v[1]) + .... + (u[n]*v[n]) then return a single value not vector

def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result + (u[i] * v[i])
        
    return result

In [41]:
vector_vector_multiplication(u,v)

14.0

In [37]:
# Have a built in function like same as my custom vector_vector_multiplication() function
u.dot(v) 

14

# Matrix-Vector Multiplication

In [52]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [46]:
U.shape

(3, 4)

In [73]:
# Note (Rules): 
# (u[0][0]*v[0]) + (u[0][1]*v[1]) + .... + (u[i][j]*v[n]) then
# (u[1][0]*v[0]) + (u[1][1]*v[1]) + .... + (u[i][j]*v[n]) then 
# return a vector
def matrix_vector_multiplication (U, v):
    assert U.shape[1] == v.shape[0] # checking column by column
    num_rows = U.shape[0] # row counting 
    result = np.zeros(num_rows)
    for i in range(num_rows): # get matrix single row
        result[i] = vector_vector_multiplication(U[i],v) # pass matrix single row and vector in existing function which is calculate vector vector multiply 
    return result

In [72]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [75]:
# Have a built in function like same as my custom matrix_vector_multiplication() function
U.dot(v)

array([14,  5,  5])